### ISSUE TITLE
"Go back" button does not work correctly for certain circumtances

### ISSUE THREAD

**Issue by anthonykhoa** [garageScript/c0d3-app#1181] opened 2021-11-12 20:05 UTC
Currently the `Go back` button is implemented by using `router.back`, which executes `history.back`. According to [the docs](https://developer.mozilla.org/en-US/docs/Web/API/History/back), `if there is no previous page, this method call does nothing.`

Consider these scenarios:

1) User is on `facebook.com`, then decides to enter https://www.c0d3.com/review/js4 into the address bar. When the user lands on https://www.c0d3.com/review/js4, if they click `go back`, the user will go back to `facebook.com`. I think it's weird for the `go back` button to redirect you to the last website you were on, even if it wasn't c0d3.com

2)  A user is on discord and notices a submission review post by the c0d3 bot. The user clicks on the link to review -- clicking on the link opens up a new tab for the user. When on the review page, if the user clicks `go back`, then nothing will happen because the first history of that tab is opening the review page. The button should do something when clicked, or else it can be perceived as broken

Here is where the `Go back` button is implemented:
https://github.com/garageScript/c0d3-app/blob/39e250c47adb3d4ed137d311c6db9dc3305be992/components/LessonTitleCard.tsx#L50

# Proposals

1) If a user clicks `go back` but the redirection url is not `c0d3.com` domain, then redirect go c0d3 homepage. If there is no `history` for the `go back` button to utilize to redirect, then just redirect back to c0d3 homepage

**Comment by songz** [comment] 2022-01-15 23:34
I actually disagree here. If I'm on facebook, and I went to c0d3.com. When I hit back I would expect to go back to facebook it's the logical action flow. Doing anything else feels really awful and creates unexpected behavior in the end user. I don't think users would expect that after landing on c0d3.com, they could never go back to the previous site they came from.

**Comment by flacial** [comment] 2022-01-16 00:44
In my case, I got frustrated by being pushed out of c0d3 when I hit the back button. And being pushed to c0d3 seems out of logic. 

I suggest we rethink whether a "Go back" button is actually necessary. The student can either click the browser's back button or use the keyboard shortcuts. 

If I'm in `/curriculum/js0/` and I hit the back button, I expect to go back to `/curriculum/` instead of whatever was previously in the history. Which can also be done by clicking the navbar `curriculum` button.

**Comment by songz** [comment] 2022-01-16 03:30
@anthonykhoa regarding your comments:

1. User is on facebook.com, then decides to enter https://www.c0d3.com/review/js4 into the address bar. When the user lands on https://www.c0d3.com/review/js4, if they click go back, the user will go back to facebook.com. <- this is expected behavior of back button

2. A user is on discord and notices a submission review post by the c0d3 bot. The user clicks on the link to review -- clicking on the link opens up a new tab for the user. When on the review page, if the user clicks go back, then nothing will happen because the first history of that tab is opening the review page. <- This is expected behavior of back button.

I did some research:

[Google chrome to stop back button hijacking on HN](https://news.ycombinator.com/item?id=18711452): One of the comment reads:  "Entries that are added to the back/forward list **without the user's intention** are marked to be skipped on subsequent back button invocations.". - Our proposed solution is adding a back history without the user's intention so it feels wrong

According [to this UX design pattern](https://baymard.com/blog/back-button-expectations), users expect the “Back” button to take them back to what they perceived to be their previous page.

**Comment by flacial** [comment] 2022-01-29 07:55
@anthonykhoa What do you vote for?

**Comment by songz** [comment] 2022-01-30 11:15
closing issue, please reopen if anyone feels strongly about this.

**Closed by songz** 2022-01-30 11:15 UTC
Labels: bug
