### ISSUE TITLE
Discord link shows incorrect number of users online

### ISSUE THREAD

**Issue by tangjurine** [garageScript/c0d3-app#1191] opened 2021-12-07 02:59 UTC
On https://www.c0d3.com/curriculum , when scrolling right, there is a banner for a discord link.

![image](https://user-images.githubusercontent.com/25800987/144957868-f88f0711-9636-4fce-a351-996ec8d9c251.png)

The link shows 0 members being online, but when clicking on "Join", the discord website is shown and there it says there are a lot of members online.

![image](https://user-images.githubusercontent.com/25800987/144958078-42610fb5-746e-4e89-9d49-a44e321d66a5.png)

I am using Chrome and Windows 10.

**Comment by SlyBouhafs** [comment] 2021-12-26 19:21
Hey @tangjurine, i tested it on different browsers and i couldn't reproduce it, is the issue still happening?

**Comment by songz** [comment] 2022-01-09 05:19
closing because it may have been an issue on discord's widget (or api) out of our control

**Closed by songz** 2022-01-09 05:19 UTC
Labels: bug, UX
