### ISSUE TITLE
Prevent users from approving/rejecting submissions for modules they haven't passed yet.

### ISSUE THREAD

**Issue by pmulard** [garageScript/c0d3-app#446] opened 2020-12-17 21:42 UTC
Users can access and approve of submissions for modules they haven't passed yet. If clicking the 'review code' link in mattermost, the user can see all submissions (including others') and accept or reject them.
![image](https://user-images.githubusercontent.com/45550174/102547103-86ac8c00-406d-11eb-9135-f43128cda775.png)
![image](https://user-images.githubusercontent.com/45550174/102547162-a0e66a00-406d-11eb-860d-a562d99d1229.png)
![image](https://user-images.githubusercontent.com/45550174/102547193-af348600-406d-11eb-9201-8821d4aeda4e.png)

**Comment by ggwadera** [comment] 2020-12-17 22:14
Duplicate of #268

PR #434 currently awaiting review fixes this.

**Comment by ggwadera** [comment] 2020-12-18 22:02
PR #434 was merged which fixed this issue, closing this now.

**Closed by ggwadera** 2020-12-18 22:02 UTC
