### ISSUE TITLE
Refactoring codebase into microservices

### ISSUE THREAD

**Issue by anthonykhoa** [garageScript/c0d3-app#1202] opened 2021-12-18 13:11 UTC
A refactoring of the codebase has been proposed. This issue is created so that conversations about this topic(`as well as decisions that will be made`) can be documented here.

**Comment by anthonykhoa** [comment] 2021-12-18 13:19
I propose we divide the codebase like so:

1) graphql server -- all the resolvers we need
2) proxy server -- this server will pass any graphql calls to the graphql server. Otherwise non-graphql server related things can go here. For example get/post routes can go here
3) client experience app. This will contain front end things like react components

**Comment by tomrule007** [comment] 2021-12-18 16:46
One of the big benifits from the Nextjs framework IMO is it is makes big architecture decisions for you.

Any code in `pages/api` folder is really an AWS Lambda functions! It automatically detects which dependencies are needed for that api call and makes a stripped down build for you.

I think any attempt to split the repo into separate services will just limit all the features NextJS is providing. 

Ie there newest version just added Edge/Middleware function support so you can run code on a CDN.

**Comment by coltonehrman** [comment] 2021-12-18 22:08
> One of the big benifits from the Nextjs framework IMO is it is makes big architecture decisions for you.
> 
> Any code in `pages/api` folder is really an AWS Lambda functions! It automatically detects which dependencies are needed for that api call and makes a stripped down build for you.
> 
> I think any attempt to split the repo into separate services will just limit all the features NextJS is providing.
> 
> Ie there newest version just added Edge/Middleware function support so you can run code on a CDN.

I agree with you that NextJS does a lot and does it well.

I don't think the argument here is to necessarily "remove NextJS" but instead, break up the platform in to modular pieces (microservice architecture).
There are several reasons why we might want to do this:
1. Splits responsibilities
2. Easier to maintain both sides as they should be slimmed down and focus only on what they care about
3. De-couples the backend from the client app, making the backend more useable in other situations (Ex. dev/staging environment, public accessible API for students and 3-rd parties)
4. Having more flexibility with the backend to re-architect it in a way that best suits is (Ex. lambdas, load balanced servers that are highly available)
5. I think 1 point that we should all be focusing on is the GOAL of c0d3 itself. In my opinion, the goal is to teach and train people to become software engineers, the means to that goal are our lessons and engineering team and projects the team gets to build and work on. If we introduce more technologies and concepts, we have more opportunities to teach people and expand everyones knowledge and at the end, make everyone a better engineer. #NewChallengesFTW!

**Comment by songz** [comment] 2021-12-18 23:33
@coltonehrman if you were the only engineering on c0d3 right now, would you still recommend your suggestion and then switch from services to service depending on what you are working on?

**Comment by coltonehrman** [comment] 2021-12-18 23:42
> @coltonehrman if you were the only engineer on c0d3 right now, would you still recommend your suggestion and then switch from services to service depending on what you are working on?

Depends on additional context.

If I'm trying to push out features fast and get something going, I would say no.

If I am only worried about maintaining the current systems, and slowly building on it, I would say yes.

**Comment by ggwadera** [comment] 2021-12-19 23:09
Besides what's already been said about NextJS, another benefit is that they manage all the deployments and infrastructure for us (except for our database), including preview deployments for PRs, and it's all for zero cost! 

Going the microservices would give us more flexibility yes, but that also means that we would need someone to maintain all that up and running, and c0d3 engineers come and go all the time, so there's a risk of something going down and no one able to do something. Documentation might help but it might also become outdated if we forget to update it after changing something. For some examples of issues we already had:
- everything going down after an unexpected VPS reboot
- TLS certificate expiring, preventing users from reaching the site
- freedomains.dev current issue with SSH keys that we can fix temporarily but no one was able to look into the cause yet

I agree that it would be interesting to teach about our system architecture and how we use microservices and everything, but from an operational point of view unfortunately I believe we don't have too much human resources to maintain everything.

Honestly the biggest issues to me would be the code organization and snapshots needlessly including the entire page. And to fix those issues it would be a lot easier than redoing our architecture.

I'm sorry to be the pessimist here but it's important to think about the pros and cons of big decisions like this. Unfortunately I'm not able to contribute much these past days, but I wish you all good luck if the team decides on going the microservice way. That would be quite a challenge and it would be very interesting to see the results of that 😊

**Comment by songz** [comment] 2022-01-09 04:57
> freedomains.dev current issue with SSH keys that we can fix temporarily but no one was able to look into the cause yet

Closing this issue because we don't have enough bandwidth to entertain this idea.

**Closed by songz** 2022-01-09 04:57 UTC
